import Vision from "../layout/VisionLayout";

export const ROUTES = {
  main: "/",
  login: "/login",
  register: "/register",
  auth: "/auth",
  managerBlogs: "manager-blog",
  managerUsers: "manager-user",
  createBlog: "create-blog",
  editUser: "edit-user/:id",
  editBlog: "edit-blog/:slug",
  settings: "settings",
  post: "/post/:slug",
  MainPage: "/MainPage",
  SearchPost: "/search/:query",
  Mission: "/mission",
  Activity: "/Activity",
  Vision: "/Vision",
  Letter: "/Letter",
  tuyenDung: "/tuyen-dung",
  thongBaoBaoChi: "/thong-cao-bao-chi",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  suckhoecongdong: "/suc-khoe-cong-dong",
  hoTroSinhKe: "/ho-tro-sinh-ke",
  anSinhXaHoi: "/an-sinh-xa-hoi",
  album: "album",
  addAlbum: "add-album",
  AlbumPage: "album-page/:id",
  ImageGallery: "album-all",
  ImagePreview: "album/:id",
} as const;
